=== sujirsachin/Recipe-Assignment-Using-XML/recipe.dtd
<!DOCTYPE recipe
[
<!ELEMENT Ingredients ( #PCDATA ) >

<!ELEMENT Procedure ( #PCDATA ) >

<!ELEMENT Recipe_Name ( #PCDATA ) >

<!ELEMENT Recipes (Ingredients | Procedure | Recipe_Name | Serving_Size | Tip | pic1 | pic2 | pic3 )* >

<!ELEMENT Serving_Size ( #PCDATA ) >

<!ELEMENT Tip ( #PCDATA ) >

]>

=== sujirsachin/Recipe-Assignment-Using-XML/recipe.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE recipe SYSTEM "recipe.dtd">
<?xml-stylesheet type="text/xsl" href="recipe.xslt"?>
<Recipes>
<Recipe>
<photo>2.jpg</photo>
<Recipe_Name>
Hoisin Glazed Salmon with Asian Red Cabbage Slaw
</Recipe_Name>

<Serving_Size>Serves: 4people </Serving_Size>

<Ingredients>Four 6-7 ounce boneless, skinless salmon fillets</Ingredients>
<Ingredients>Approx. 1/3-1/2 cup bottled hoisin sauce</Ingredients>
<Ingredients>4 cups thinly sliced red cabbage</Ingredients>
<Ingredients>1 medium jalapeno pepper, deseeded and thinly sliced</Ingredients>
<Ingredients>1 Tbs peeled, minced fresh ginger</Ingredients>
<Ingredients>1 cup chopped fresh cilantro</Ingredients>
<Ingredients>2 Tbs light brown sugar</Ingredients>
<Ingredients>2 Tbs sesame oil</Ingredients>
<Ingredients>1 large lime, juiced</Ingredients>
<Ingredients>2 Tbs toasted sesame seeds (optional)</Ingredients>
<Ingredients>Salt to taste</Ingredients>
<Procedure> Procedure </Procedure>


<Procedure>Step1: Use a large mixing bowl to combine 4 cups thinly sliced red cabbage with 1 deseeded and thinly sliced jalapeno pepper, 1 Tbs finely minced fresh ginger, 1 cup chopped fresh cilantro, 2 Tbs light brown sugar, salt to taste, 2 Tbs sesame oil and a sprinkling of sesame seeds if you have them and then squeeze the juice of one whole large lime into the mix and toss to combine. 
</Procedure>
<Procedure>Step2: You can make the slaw 1-2 hours ahead of time and keep it cold in the fridge and then, when you are ready to eat, preheat the oven to 400 degrees and place the boneless, skinless salmon fillets into a oiled baking dish and brush the those with a good layer of the hoisin and place the dish on the center rack of the preheated oven. 
</Procedure>
<Procedure>Step3: Depending on the thickness of the salmon it could take 10-12 minutes to bake and, once the fish is cooked to your liking, it's time to eat.
</Procedure>
<Tip> Hint: You can make the slaw 1-2 hours ahead of time, and keep it cold in the fridge, to allow the flavors to develop. Add 1/4-inch water to the baking pan with the fish before baking to help keep any hoisin sauce from burning in the baking dish. </Tip>
</Recipe>

<Recipe>
<photo>1.jpg</photo>
<Recipe_Name>
Chicken Linguine with Broccoli
</Recipe_Name>

<Serving_Size>Serves: 4-6 people </Serving_Size>

<Ingredients>Four 6-7 ounce boneless, skinless salmon fillets</Ingredients>
<Ingredients>Approx. 1/3-1/2 cup bottled hoisin sauce</Ingredients>
<Ingredients>4 cups thinly sliced red cabbage</Ingredients>
<Ingredients>1 medium jalapeno pepper, deseeded and thinly sliced</Ingredients>
<Ingredients>1 Tbs peeled, minced fresh ginger</Ingredients>
<Ingredients>1 cup chopped fresh cilantro</Ingredients>
<Ingredients>2 Tbs light brown sugar</Ingredients>
<Ingredients>2 Tbs sesame oil</Ingredients>
<Ingredients>1 large lime, juiced</Ingredients>
<Ingredients>2 Tbs toasted sesame seeds (optional)</Ingredients>
<Ingredients>Salt to taste</Ingredients>
<Procedure> Procedure </Procedure>


<Procedure>Step1: Get a large pot of salted water going on the stove top for cooking the linguine and, while that is coming up to a boil, finely mince 2 Tbs garlic, chop about 1/2 cup fresh parsley and cut 4 cups broccoli into small florets and then, lastly, cut the boneless, skinless chicken breast meat into 1/2-inch cubes. 
</Procedure>
<Procedure>Step2: Season the cubed chicken with salt and pepper and give it a light dusting of all-purpose flour and then cook it in batches in a deep, heavy bottomed pot in a little olive oil on medium to medium high heat. 
</Procedure>
<Procedure>Step3: Once the water comes to a boil, add the linguine and stir that around to keep it from sticking.
</Procedure>
<Procedure>Step4: Once all of the chicken is lightly browned, and out of the pan and resting on a clean plate, add 3 Tbs butter to the chicken pot, let that melt down. Add the minced garlic and cook that for a minute or so and then add about 3 cups chicken stock and bring it up to a simmer. 
</Procedure>
<Procedure>Step5: Once the stock does come to a simmer, add the broccoli florets and add the chicken back to the pan. 
</Procedure>
<Procedure>Step6: Keep your eye on the linguine and drain that when it's done and, once the broccoli and chicken are cooked through, add the drained, still hot linguine to that pot, add a little more olive oil, the chopped parsley, add salt and red pepper flakes to taste and toss to coat.
</Procedure>
<Procedure>Step7: Serve in individual bowls with grated parmesan cheese.
</Procedure>  
<Tip> Hint: You can make this without the broccoli if you like </Tip>
</Recipe>
<Recipe>

<photo>3.jpg</photo>
<Recipe_Name> Paneer Ghee Roast </Recipe_Name>
<pic3></pic3>
<Serving_Size>Serves: 3 people </Serving_Size>

<Ingredients>For Chettinad Masala
5 Kashmiri Chilies:  </Ingredients>
<Ingredients>1 tsp Coriander Seeds </Ingredients>
<Ingredients>1 tsp cumin seeds </Ingredients>
<Ingredients>1 tsp Fennel Seeds </Ingredients>
<Ingredients>1 tsp Pepper Corns </Ingredients>
<Ingredients>4-5 Dry red chilies </Ingredients>
<Ingredients>1 inch Ginger </Ingredients>
<Ingredients>2 Cloves of Garlic </Ingredients>
<Ingredients>1 Tbsp Lemon juice </Ingredients>
<Ingredients>1/4 tsp Turmeric Powder </Ingredients>
<Ingredients>To Paneer Ghee Roast: 
4 Tbsp Ghee / Clarified butter </Ingredients>
<Ingredients>1(150g) Onion </Ingredients>
<Ingredients>1/4 cup Yogurt / Curd </Ingredients>
<Ingredients>Curry Leaves for Garnishing </Ingredients>
<Ingredients>1 tsp coriander powder </Ingredients>
<Ingredients>Salt to taste </Ingredients>
<Procedure> Procedure </Procedure>
<Procedure>Step1: Roast the spices and grind them with turmeric,ginger, garlic, and water to make Chettinad Masala
</Procedure>
<Procedure>Step2: Melt ghee and fry the paneer and set aside
</Procedure>
<Procedure>Step3: In the same ghee saute onions and add then add the masala , yogurt and cook until the raw smell is gone
</Procedure>
<Procedure>Step4: Add the roasted paneer and mix well with the masala
</Procedure>
<Procedure>Step5: Add Curry leaves for garnishing.
</Procedure>
<Procedure>Step6: Paneer Roast recipe is ready to be served as a side for rice and chapathi.
</Procedure>
<Tip> Hint: Try this recipe with chicken or shrimp, especially crab. </Tip>
</Recipe>
</Recipes>
